version: '3.8'

services:
  # # 1. Ta Gateway API (Point d'entrée unique)
  # kong:
  #   image: kong:3.4-alpine
  #   container_name: kong-gateway
  #   user: "root"
  #   environment:
  #     KONG_DATABASE: "off"
  #     KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
  #   volumes:
  #     - ./config:/usr/local/kong/declarative/
  #   ports:
  #     - "8000:8000" # Proxy HTTP (Tes agents appelleront ce port)
  #     - "8443:8443" # Proxy HTTPS
  #     - "8001:8001" # Admin API (Pour vérifier la config)
  #   restart: always

  # 2. Ton Backend Python (FastAPI)
  backend:
    build: ./MyAPI
    container_name: magasin_elec_backend
    volumes:
      - ./MyAPI:/workdir
      - ./MyAPI/catalog:/workdir/catalog
    env_file: .env
    ports:
      - "8000:8000" 
    restart: always

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      # --- AUTHENTIFICATION ---
      - N8N_BASIC_AUTH_ACTIVE=false
      
      # --- CONFIGURATION RÉSEAU ---
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # Note : Si tu utilises ngrok, l'URL ci-dessous devra correspondre à ton URL ngrok plus tard
      - WEBHOOK_URL=https://poet-snarl-impolite.ngrok-free.dev/
      
      # --- ACTIVATION JS-YAML (L'étape cruciale pour ton erreur) ---
      - NODE_FUNCTION_ALLOW_EXTERNAL=js-yaml
      
    ports:
      - "5678:5678"
    volumes:
      - ./bd_vectoriel/n8n_data:/home/node/.n8n
    # On enlève depends_on pour supprimer le lien avec kong et mcp-server
    # On garde networks si tu as d'autres services (comme Pinecone local ou une DB)

  # 4. Redis (Pour la mémoire de tes agents)
  redis:
    image: redis:alpine
    container_name: magasin_elec_redis